name: showerpy
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiobotocore=2.19.0
  - aiohappyeyeballs=2.4.6
  - aiohttp=3.11.12
  - aioitertools=0.12.0
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - astropy=7.0.1
  - astropy-base=7.0.1
  - astropy-iers-data=0.2025.2.10.0.33.26
  - asttokens=3.0.0
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - botocore=1.36.3
  - bottleneck=1.4.2
  - bqplot=0.12.43
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dask-core=2025.2.0
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - double-conversion=3.3.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.4
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2025.2.0
  - gast=0.4.0
  - gflags=2.2.2
  - glog=0.7.1
  - graphite2=1.3.13
  - h2=4.2.0
  - h5py=3.12.1
  - harfbuzz=10.2.0
  - hdf5=1.14.4
  - hpack=4.1.0
  - html5lib=1.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - ipydatagrid=1.4.0
  - ipykernel=6.29.5
  - ipython=8.31.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jmespath=1.0.1
  - jplephem=2.21
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=19.0.0
  - libarrow-acero=19.0.0
  - libarrow-dataset=19.0.0
  - libarrow-substrait=19.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20240808
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.0
  - libpciaccess=0.18
  - libpng=1.6.45
  - libpq=17.2
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4-c=1.10.0
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mpmath=1.3.0
  - multidict=6.1.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - numpy=2.2.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.50
  - propcache=0.2.1
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=19.0.0
  - pyarrow-core=19.0.0
  - pycparser=2.22
  - pyerfa=2.0.1.5
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pyside6=6.8.1
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.8.1
  - re2=2024.07.02
  - readline=8.2
  - s2n=1.5.11
  - s3fs=2025.2.0
  - scipy=1.15.1
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - stack_data=0.6.3
  - tk=8.6.13
  - toolz=1.0.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - traittypes=0.2.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - corsikaio==0.5.0
      - eventio==1.14.0
      - zstandard==0.23.0
